% Batch run of rm_trunk_edge
% 
% Zhan Li <zhanli86@bu.edu>
% Wed Nov 18 22:05:04 EST 2015

clear;

in_trk_pts_files = { ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_124_grd_rm_trk.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_135_grd_rm_trk.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_183_grd_rm_trk.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_187_grd_rm_trk.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_192_grd_rm_trk.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_241_grd_rm_trk.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_247_grd_rm_trk.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/Aug3_BFP_tape_id_267_grd_rm_trk.txt' ...
                   };

out_trk_pts_files = { ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_124_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_135_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_183_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_187_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_192_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_241_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_247_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_267_grd_rm_trk_edge_rm.txt' ...
                    };

N = length(in_trk_pts_files);
for n = 1:N
    trk_pts_file = in_trk_pts_files{n};
    out_trk_pts_file = out_trk_pts_files{n};
    rm_trunk_edge(trk_pts_file, out_trk_pts_file);
end
