% batch run of trunk_dual_intensity
% 
% Zhan Li <zhanli86@bu.edu>
% Wed Nov 18 22:41:34 EST 2015

clear;

tree_pts_files = { ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_124_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_135_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_183_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_187_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_247_grd_rm_trk_edge_rm.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_267_grd_rm_trk_edge_rm.txt' ...
                    };

out_profile_files = { ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_124_grd_rm_trk_edge_rm_profile.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_135_grd_rm_trk_edge_rm_profile.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_183_grd_rm_trk_edge_rm_profile.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_187_grd_rm_trk_edge_rm_profile.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_247_grd_rm_trk_edge_rm_profile.txt', ...
'/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/Aug3_BFP_tape_id_267_grd_rm_trk_edge_rm_profile.txt' ...
                    };

N = length(tree_pts_files);
all_layer_stats = cell(N, 1);
for n=1:N
    all_layer_stats{n, 1} = trunk_dual_intensity(tree_pts_files{n}, out_profile_files{n});
end
all_layer_stats = cell2mat(all_layer_stats);

layer_stats_file = '/projectnb/echidna/lidar/zhanli86/workspace/data/projects/brisbane-dual-wavelength-spectra/gold0101-dwel-data/gold0101-dwel-data-pts/grd-rm/trunk-extraction/edge-rm/gold0101_dwel_trk_layer_stats.txt';

fid = fopen(layer_stats_file, 'w');
% layer stats: num_pts, mean_rg, std_rg, min_nir, max_nir, mean_nir, std_nir, min_swir,
% max_swir, mean_swir, std_swir, min_ndi, max_ndi, mean_ndi, std_ndi
fprintf(fid, 'file,num_pts,mean_rg,std_rg,min_nir,max_nir,mean_nir,std_nir,min_swir,max_swir,mean_swir,std_swir,min_ndi,max_ndi,mean_ndi,std_ndi,mean_cos_zen,std_cos_zen,min_zen,max_zen,mean_zen,std_zen\n');
for n=1:N
    [~, tmpstr, ~] = fileparts(tree_pts_files{n});
    fprintf(fid, ['%s,',repmat('%.3f,', 1, 20), '%.3f\n'], tmpstr, (all_layer_stats(n, :))');
end
fclose(fid);
